#!/bin/bash
# =============================================================================
# setup_usbguard.sh
# One-time setup for USB device authorization on Raspberry Pi
# Repository: https://github.com/phoggbergActual/Tools/tree/main/USBGuard
# =============================================================================
#
# PURPOSE:
#   Installs and configures USBGuard to block unauthorized USB devices
#   at the kernel level before they can function.
#
#   Defends against:
#     - BadUSB attacks (malicious device presenting as a keyboard)
#     - RubberDucky style keystroke injection
#     - Pi Zero or similar device presenting as HID after boot
#     - Any unauthorized USB device type
#
# HOW IT WORKS:
#   1. Installs usbguard
#   2. Generates a policy from currently connected devices (your whitelist)
#   3. Starts the daemon — any device not in the policy is blocked
#   4. Installs a helper script for authorizing new legitimate devices
#
# IMPORTANT: Run this with all your normal USB devices connected.
#   Any device connected at setup time will be authorized.
#   Devices connected later will be blocked until explicitly authorized.
#
# USAGE:
#   wget https://raw.githubusercontent.com/phoggbergActual/Tools/main/USBGuard/setup_usbguard.sh
#   cat setup_usbguard.sh
#   sudo bash setup_usbguard.sh
#
# =============================================================================

set -euo pipefail

if [[ "$EUID" -ne 0 ]]; then
    echo "Please run as root: sudo bash setup_usbguard.sh"
    exit 1
fi

PI_USER="${SUDO_USER:-pi}"
BASE_URL="https://raw.githubusercontent.com/phoggbergActual/Tools/main/USBGuard"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
POLICY_FILE="/etc/usbguard/rules.conf"
LOG_FILE="/var/log/usbguard_setup.log"

echo ""
echo "========================================================"
echo "  USBGuard Setup"
echo "========================================================"
echo ""
echo "  IMPORTANT: Make sure all your normal USB devices are"
echo "  connected right now before continuing. Any device"
echo "  connected at this point will be authorized. Everything"
echo "  else will be blocked after setup."
echo ""
read -rp "  Are all your normal USB devices connected? (yes/no): " CONFIRM

if [[ "$CONFIRM" != "yes" ]]; then
    echo ""
    echo "  Connect your devices and run setup again."
    exit 0
fi

echo ""

# --- Step 1: Install USBGuard ------------------------------------------------
echo "Step 1: Installing USBGuard..."
apt-get update -qq
apt-get install -y usbguard usbguard-tools
echo "  Done."

# --- Step 2: Generate policy from current devices ---------------------------
echo "Step 2: Generating authorization policy from connected devices..."
echo "  The following devices will be authorized:"
echo ""

# List current devices for review
usbguard list-devices 2>/dev/null | while IFS= read -r line; do
    echo "    $line"
done || echo "    (no devices currently connected)"

echo ""

# Generate the policy
usbguard generate-policy > "$POLICY_FILE" 2>/dev/null || {
    echo "  Warning: Could not auto-generate policy. Creating permissive default."
    # Fallback: allow all currently connected devices by class
    cat > "$POLICY_FILE" << 'POLICY'
# USBGuard policy — generated by setup_usbguard.sh
# Allow HID devices (keyboard, mouse) connected at setup time
allow with-interface equals { 03:*:* }
# Allow mass storage connected at setup time
allow with-interface equals { 08:*:* }
# Block everything else
block
POLICY
}

echo "  Policy written to $POLICY_FILE"

# Append a catch-all block rule if not already present
if ! grep -q "^block$" "$POLICY_FILE" 2>/dev/null; then
    echo "" >> "$POLICY_FILE"
    echo "# Block all other devices not explicitly authorized above" >> "$POLICY_FILE"
    echo "block" >> "$POLICY_FILE"
fi

echo "  Done."

# --- Step 3: Configure USBGuard logging -------------------------------------
echo "Step 3: Configuring USBGuard..."

# Enable audit logging so we can see what gets blocked
if [[ -f /etc/usbguard/usbguard-daemon.conf ]]; then
    # Enable audit log
    sed -i 's/^AuditFilePath=.*/AuditFilePath=\/var\/log\/usbguard-audit.log/' \
        /etc/usbguard/usbguard-daemon.conf 2>/dev/null || true
    # Set implicit policy to block (default is block, but make it explicit)
    sed -i 's/^ImplicitPolicyTarget=.*/ImplicitPolicyTarget=block/' \
        /etc/usbguard/usbguard-daemon.conf 2>/dev/null || true
fi

touch /var/log/usbguard-audit.log
chmod 640 /var/log/usbguard-audit.log

echo "  Done."

# --- Step 4: Start and enable USBGuard daemon --------------------------------
echo "Step 4: Starting USBGuard daemon..."

systemctl enable usbguard
systemctl start usbguard

# Verify it started
if systemctl is-active --quiet usbguard; then
    echo "  USBGuard is running."
else
    echo "  WARNING: USBGuard failed to start."
    echo "  Check: sudo systemctl status usbguard"
    echo "  Check: sudo journalctl -u usbguard -n 20"
fi

# --- Step 5: Install helper script ------------------------------------------
echo "Step 5: Installing authorization helper..."

HELPER_SCRIPT="/usr/local/bin/usbguard_helper.sh"

# Download helper if not present locally
if [[ ! -f "$SCRIPT_DIR/usbguard_helper.sh" ]]; then
    wget -q "$BASE_URL/usbguard_helper.sh" -O "$HELPER_SCRIPT" 2>/dev/null || \
    # Create inline if download fails
    cat > "$HELPER_SCRIPT" << 'HELPER'
#!/bin/bash
# USBGuard authorization helper
# Usage: sudo usbguard_helper.sh

echo ""
echo "=== Blocked USB Devices ==="
BLOCKED=$(usbguard list-devices --blocked 2>/dev/null)

if [[ -z "$BLOCKED" ]]; then
    echo "No devices currently blocked."
    exit 0
fi

echo "$BLOCKED"
echo ""
read -rp "Enter device ID to authorize (or q to quit): " DEVICE_ID

if [[ "$DEVICE_ID" == "q" ]]; then
    exit 0
fi

echo ""
read -rp "Make this permanent? (yes/no): " PERMANENT

if [[ "$PERMANENT" == "yes" ]]; then
    usbguard allow-device -p "$DEVICE_ID" && echo "Device $DEVICE_ID authorized permanently."
else
    usbguard allow-device "$DEVICE_ID" && echo "Device $DEVICE_ID authorized for this session."
fi
HELPER
else
    cp "$SCRIPT_DIR/usbguard_helper.sh" "$HELPER_SCRIPT"
fi

chmod +x "$HELPER_SCRIPT"

# Add convenient alias to the pi user's bashrc
ALIAS_LINE="alias usb-allow='sudo /usr/local/bin/usbguard_helper.sh'"
if ! grep -q "usb-allow" "/home/$PI_USER/.bashrc" 2>/dev/null; then
    echo "" >> "/home/$PI_USER/.bashrc"
    echo "# USBGuard helper alias — added by setup_usbguard.sh" >> "/home/$PI_USER/.bashrc"
    echo "$ALIAS_LINE" >> "/home/$PI_USER/.bashrc"
fi

echo "  Helper installed. Type 'usb-allow' to authorize a blocked device."

# --- Step 6: Test -----------------------------------------------------------
echo "Step 6: Verifying policy..."
echo ""
echo "  Current authorized devices:"
usbguard list-devices --allowed 2>/dev/null | while IFS= read -r line; do
    echo "    $line"
done || echo "    (none — this may indicate an issue)"

echo ""

# Log setup completion
echo "$(date '+%Y-%m-%d %H:%M:%S') USBGuard setup completed by $PI_USER" >> "$LOG_FILE" 2>/dev/null || true

# --- Done -------------------------------------------------------------------
echo ""
echo "========================================================"
echo "  USBGuard is active."
echo "========================================================"
echo ""
echo "  Authorized devices: currently connected devices only"
echo "  Everything else:    blocked at kernel level"
echo ""
echo "  When you plug in a new legitimate device:"
echo "    usb-allow                    (interactive helper)"
echo "  or:"
echo "    sudo usbguard list-devices   (see blocked devices)"
echo "    sudo usbguard allow-device -p DEVICE_ID  (authorize permanently)"
echo ""
echo "  Logs:"
echo "    /var/log/usbguard-audit.log  (all USB events)"
echo ""
echo "  Works best with USBsentry (ClamAV scan on authorized drives)"
echo "    https://github.com/phoggbergActual/Tools/tree/main/USBsentry"
echo ""
