#!/bin/bash
# =============================================================================
# setup_pimaintain.sh
# One-time setup for biweekly maintenance on Raspberry Pi
# Repository: https://github.com/phoggbergActual/Tools/tree/main/PiMaintain
# =============================================================================
#
# PURPOSE:
#   Installs and configures biweekly automated maintenance:
#     - OS package updates (apt)
#     - ClamAV virus definition updates
#     - Full filesystem virus scan
#     - Email report to your Gmail address
#
# USAGE:
#   wget https://raw.githubusercontent.com/phoggbergActual/Tools/main/PiMaintain/setup_pimaintain.sh
#   cat setup_pimaintain.sh
#   sudo bash setup_pimaintain.sh your.email@gmail.com
#
# GMAIL APP PASSWORD:
#   You need a Google App Password, not your main Gmail password.
#   myaccount.google.com > Security > 2-Step Verification > App Passwords
#   Create one for Mail on Linux device.
#
# =============================================================================

set -euo pipefail

if [[ "$EUID" -ne 0 ]]; then
    echo "Please run as root: sudo bash setup_pimaintain.sh your.email@gmail.com"
    exit 1
fi

# Email address is required as $1
REPORT_EMAIL="${1:-}"
if [[ -z "$REPORT_EMAIL" ]]; then
    echo "ERROR: Email address required."
    echo "Usage: sudo bash setup_pimaintain.sh your.email@gmail.com"
    exit 1
fi

PI_USER="${SUDO_USER:-pi}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_URL="https://raw.githubusercontent.com/phoggbergActual/Tools/main/PiMaintain"

echo ""
echo "========================================================"
echo "  PiMaintain Setup"
echo "  Reports will be sent to: $REPORT_EMAIL"
echo "========================================================"
echo ""

# --- Step 1: Install packages ------------------------------------------------
echo "Step 1: Installing required packages..."
apt-get update -qq
apt-get install -y clamav clamav-daemon msmtp msmtp-mta
echo "  Done."

# --- Step 2: Configure Gmail via msmtp --------------------------------------
echo "Step 2: Configuring Gmail for report delivery..."
echo ""
echo "  You need a Google App Password (not your main Gmail password)."
echo "  Go to: myaccount.google.com > Security > 2-Step Verification > App Passwords"
echo "  Create one for Mail on Linux device."
echo ""
read -rsp "  Enter your Gmail App Password (input hidden): " GMAIL_APP_PASSWORD
echo ""

cat > /etc/msmtprc << MSMTP_CONF
# msmtp configuration — generated by setup_pimaintain.sh
defaults
auth           on
tls            on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile        /var/log/msmtp.log

account        gmail
host           smtp.gmail.com
port           587
from           $REPORT_EMAIL
user           $REPORT_EMAIL
password       $GMAIL_APP_PASSWORD

account default : gmail
MSMTP_CONF

chmod 600 /etc/msmtprc
chown root:root /etc/msmtprc
echo "  Gmail configured."

# --- Step 3: Install maintenance script -------------------------------------
echo "Step 3: Installing maintenance script..."

# Download if not present locally
if [[ ! -f "$SCRIPT_DIR/maintenance.sh" ]]; then
    wget -q "$BASE_URL/maintenance.sh" -O /tmp/maintenance.sh
    MAINT_SCRIPT="/tmp/maintenance.sh"
else
    MAINT_SCRIPT="$SCRIPT_DIR/maintenance.sh"
fi

cp "$MAINT_SCRIPT" /usr/local/bin/maintenance.sh
chmod +x /usr/local/bin/maintenance.sh
chown root:root /usr/local/bin/maintenance.sh

# Create log directory
mkdir -p "/home/$PI_USER/logs"
chown "$PI_USER:$PI_USER" "/home/$PI_USER/logs"
chmod 700 "/home/$PI_USER/logs"

touch /var/log/maintenance.log
chmod 666 /var/log/maintenance.log

echo "  Done."

# --- Step 4: Install crontab -------------------------------------------------
echo "Step 4: Setting up biweekly crontab..."

# Cron entry — 2am on 1st and 15th of each month
# Email address is passed as $1 to maintenance.sh
CRON_ENTRY="0 2 1,15 * * /usr/local/bin/maintenance.sh $REPORT_EMAIL >> /var/log/maintenance.log 2>&1"
CRON_TMP=$(mktemp)

crontab -l 2>/dev/null > "$CRON_TMP" || true

if ! grep -q "maintenance.sh" "$CRON_TMP"; then
    echo "# PiMaintain: biweekly system maintenance — added by setup_pimaintain.sh" >> "$CRON_TMP"
    echo "$CRON_ENTRY" >> "$CRON_TMP"
    crontab "$CRON_TMP"
    echo "  Crontab set: runs at 2am on the 1st and 15th of each month."
else
    echo "  Crontab entry already exists."
fi

rm -f "$CRON_TMP"

# --- Step 5: Send test email -------------------------------------------------
echo "Step 5: Sending test email to $REPORT_EMAIL..."

{
    echo "To: $REPORT_EMAIL"
    echo "From: pi@$(hostname)"
    echo "Subject: PiMaintain Setup Complete — $(hostname)"
    echo ""
    echo "PiMaintain is configured and active on $(hostname)."
    echo ""
    echo "Maintenance runs automatically at 2am on the 1st and 15th of each month."
    echo "Reports will be sent to this address."
    echo ""
    echo "To run a manual maintenance check:"
    echo "  sudo /usr/local/bin/maintenance.sh $REPORT_EMAIL"
    echo ""
    echo "Setup completed: $(date)"
} | msmtp "$REPORT_EMAIL" 2>/dev/null

if [[ $? -eq 0 ]]; then
    echo "  Test email sent. Check your inbox."
else
    echo "  WARNING: Test email failed."
    echo "  Check your App Password and try:"
    echo "    echo 'test' | msmtp $REPORT_EMAIL"
fi

# --- Done --------------------------------------------------------------------
echo ""
echo "========================================================"
echo "  PiMaintain is active."
echo "========================================================"
echo ""
echo "  Schedule:  2am on the 1st and 15th of each month"
echo "  Reports:   $REPORT_EMAIL"
echo ""
echo "  To run manually:"
echo "    sudo /usr/local/bin/maintenance.sh $REPORT_EMAIL"
echo ""
echo "  To check logs:"
echo "    ls ~/logs/"
echo "    cat /var/log/maintenance.log"
echo ""
